<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NixToUny.Domain\NixToUny.Domain.csproj" />
    <ProjectReference Include="..\NixToUny.Migration\NixToUny.Migration.csproj" />
  </ItemGroup>
</Project>
